import type { RemoteServiceType } from "../types";

export const EXTENSION_TO_LANGUAGE: Record<string, string> = {
	js: "javascript",
	ts: "typescript",
	py: "python",
	rb: "ruby",
	java: "java",
	c: "c",
	cpp: "cpp",
	h: "c",
	hpp: "cpp",
	cs: "csharp",
	go: "go",
	rs: "rust",
	swift: "swift",
	kt: "kotlin",
	scala: "scala",
	php: "php",
	sh: "bash",
	bash: "bash",
	zsh: "bash",
	ps1: "powershell",
	sql: "sql",
	html: "html",
	css: "css",
	scss: "scss",
	less: "less",
	json: "json",
	xml: "xml",
	yaml: "yaml",
	yml: "yaml",
	toml: "toml",
	md: "markdown",
	lua: "lua",
	r: "r",
	pl: "perl",
	ex: "elixir",
	exs: "elixir",
	erl: "erlang",
	clj: "clojure",
	hs: "haskell",
	ml: "ocaml",
	fs: "fsharp",
	vue: "vue",
	svelte: "svelte",
	jsx: "jsx",
	tsx: "tsx",
};

export const SERVICE_LABELS: Record<RemoteServiceType, string> = {
	webdav: "WebDAV",
	github: "GitHub",
	gitlab: "GitLab",
	gitea: "Gitea",
	generic: "Generic URL",
};
